// See https://aka.ms/new-console-template for more information
Console.ForegroundColor = ConsoleColor.Gray;
Console.WriteLine("Colorfull Heart");
Console.WriteLine("");
Console.ForegroundColor = ConsoleColor.DarkBlue;
Console.WriteLine(@"  / \     / \ ");
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine(@" /   \   /   \ ");
Console.ForegroundColor = ConsoleColor.Cyan;
Console.WriteLine(@" \    \ /    / ");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine(@"  \         / ");
Console.ForegroundColor = ConsoleColor.DarkYellow;
Console.WriteLine(@"   \       / ");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine(@"    \     / ");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine(@"     \   / ");
Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine(@"      \ / ");
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine(@"       V ");